algoritmo "ex10"
//A Loja Mamão com Açúcar está vendendo seus produtos em 5 (cinco) prestações sem juros.
//Faça um algoritmo que
//receba um valor de uma compra e mostre o valor das prestações
var

valorC,valorP: real

inicio

escreval ("A compra feita foi no valor de: ")
leia (valorC)
escreval ("")

valorP <- valorC / 5

escreva ("O valor de cada prestação (5 vezes) será de: R$")
escreva (valorP)

FIMALGORITMO

