algoritmo "ex5"

var

nome: caractere
n1, n2, n3, media: real

inicio

escreval ("Escreva o nome do aluno")
leia (nome)
escreval ("Digite a primeira nota do aluno")
leia (n1)
escreval ("Digite a segunda nota do aluno")
leia (n2)
escreval ("Digite a terceira nota do aluno")
leia (n3)

escreval (" ")
media <- (n1 + n2 + n3) / 3

escreva ("a media do aluno foi: ")
escreval (media)

fimalgoritmo
