algoritmo "ex25"

var
n1,n2: inteiro

inicio

escreval ("Digite um numero")
leia (n1)
escreval ("Digite um numero")
leia (n2)
se n1 = n2 entao
escreval ("Os numeros são iguais")
senao
se n2 > n1 entao
n1 <- n2
escreval ("Os numeros são diferentes")
escreval ("O maior numero é o ")
escreval(n1)
senao
escreval ("Os numeros são diferentes")
escreval ("O maior numero é o ")
escreval(n2)
fimse
fimse


fimalgoritmo
