algoritmo "ex15"                                                                         algoritmo "ex15"

//Faça um algoritmo que receba um número e diga se este número
//está no intervalo entre 100 e 200

var

n1 : inteiro

inicio

escreval ("Digite um numero")
leia (n1)
se (n1 > 100) e (n1 < 200) entao
escreval ("O numero estra entre 100 e 200")
senao
escreval ("O numero esta fora do intervalo")
fimse

fimalgoritmo
